server:
  port: 8090

spring:
    datasource:
        name: test
        url: jdbc:mysql://localhost:3306/jmeterplatform?characterEncoding=utf8&useSSL=false&serverTimezone=UTC
        username: root
        password: 111111
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20
    #redis
    redis:
      host : 127.0.0.1
      port : 6379
      store-type : redis

## 该配置节点为独立的节点，有很多同学容易将这个配置放在spring的节点下，导致配置无法被识别
mybatis:
  mapper-locations: classpath:mybatis/*.xml  #注意：一定要对应mapper映射xml文件的所在路径
  type-aliases-package: com.meicai.entity
  # 加载全局的配置文件
#  configLocation: classpath:mybatis/mybatis-config.xml
security:
  oauth2:
    resource:
      jwt:
        key-value:  # 注意：对应实体类的路径

#jwt
jwt:
  secret : mySecret
  tokenHead : Bearer
  header : Authorization
  expiration : 604800